series:
  - label: tensec
    interval: 10s
    keep: 3
  - label: hourly
    interval: 1h
    keep: 3
  - label: daily
    interval: 1d
    keep: 3
  - label: weekly
    interval: 1w
    keep: -1  # This is a special value that means "keep an infinite number".
