series:
  - label: tensec
    interval: 10s
    keep: 3
  - label: hourly
    interval: 1h
    keep: 3
  - label: daily
    interval: 24h  # Go's `time.ParseDuration` does not support units larger than hours.
    keep: 3
  - label: weekly
    interval: 168h
    keep: -1  # This is a special value that means "keep an infinite number".
